Don't warn about missing newline
cs50/style50 pull request #50
Opened 2017-10-29 08:45 UTC by crossroads1112

This likely needs a bit more testing (since I wrote this at 4am)

2017-10-29 19:45 UTC, kzidane requested changes

2017-10-29 19:45 UTC, kzidane commented on style50/style50.py
> +            if code[-1] != '\n':
Does this break if the file is empty?

2017-10-29 21:28 UTC, crossroads1112 commented on style50/style50.py
> +            if code[-1] != '\n':
Nice catch, fixed.

2017-10-30 02:53 UTC, kzidane approved these changes

2017-10-30 02:55 UTC, merged